# Generated by Django 4.1.5 on 2023-07-25 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
